### PR TITLE
buildbot: set workdir to . when recreating tooldirs

### PR DESCRIPTION
**Pull request by korli**
otherwise it defaults to 'build'

### CODE REVIEW

**Comment by kallisti5** [comment]
Some of our code revolves around that build directory. see:

https://github.com/haiku/infrastructure/blob/master/data/buildbot/master.cfg#L704
https://github.com/haiku/infrastructure/blob/master/data/buildbot/master.cfg#L726

Doesn't this reduce the directory depth?  @jessicah also has a bunch of changes around container builds which moves the buildtools directory which could be impacted by this.

I'm not saying it's a bad change at all... but just looks incomplete.

**Comment by waddlesplash** [comment]
This is to fix https://dev.haiku-os.org/ticket/14233 though. So not sure that's a problem here?

**Comment by korli** [comment]
The delete and create steps don't use the right base directory. They actually act on an unused directory ATM. The cross tools build step already uses a directory upwards which never gets removed. Please see the bug report referenced.

**Comment by kallisti5** [comment]
I see the excess directory... but it is generally empty. So I assume this one just prevents it from getting created?

```
[bbot@hbbot02 haiku]$  find haiku-nightlies-x86_64/ -maxdepth 3 | grep -v attributes
haiku-nightlies-x86_64/
haiku-nightlies-x86_64/build
haiku-nightlies-x86_64/generated
haiku-nightlies-x86_64/generated/build
haiku-nightlies-x86_64/generated/build/BuildConfig
haiku-nightlies-x86_64/generated/build/jamfile_cache
haiku-nightlies-x86_64/generated/build/header_cache
haiku-nightlies-x86_64/generated/build/last-built-revision
haiku-nightlies-x86_64/generated/build/haiku-revision
haiku-nightlies-x86_64/generated/build/effective-haiku-revision
haiku-nightlies-x86_64/generated/Jamfile
haiku-nightlies-x86_64/generated/objects
haiku-nightlies-x86_64/generated/objects/haiku
haiku-nightlies-x86_64/generated/objects/linux
haiku-nightlies-x86_64/generated/objects/common
haiku-nightlies-x86_64/generated/objects/catalogs
haiku-nightlies-x86_64/generated/build_packages
haiku-nightlies-x86_64/generated/build_packages/gcc_syslibs_devel-7.3.0_2018_05_01-2-x86_64
haiku-nightlies-x86_64/generated/build_packages/icu-57.1-3-x86_64
haiku-nightlies-x86_64/generated/build_packages/zlib-1.2.11-3-x86_64
haiku-nightlies-x86_64/generated/build_packages/zstd-1.3.4-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/gcc_syslibs-7.3.0_2018_05_01-2-x86_64
haiku-nightlies-x86_64/generated/build_packages/openssl-1.0.2o-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/freetype-2.9-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/fontconfig-2.12.6-2-x86_64
haiku-nightlies-x86_64/generated/build_packages/curl-7.60.0-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/mesa-17.1.7-8-x86_64
haiku-nightlies-x86_64/generated/build_packages/ncurses6-6.0-3-x86_64
haiku-nightlies-x86_64/generated/build_packages/libedit-20170329_3.1-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/glu-9.0.0-7-x86_64
haiku-nightlies-x86_64/generated/build_packages/expat-2.2.5-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/fluidlite_devel-1.0.0-3-x86_64
haiku-nightlies-x86_64/generated/build_packages/libvorbis-1.3.5-5-x86_64
haiku-nightlies-x86_64/generated/build_packages/openexr-2.2.1-2-x86_64
haiku-nightlies-x86_64/generated/build_packages/ilmbase-2.2.1-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/libicns-0.8.1-6-x86_64
haiku-nightlies-x86_64/generated/build_packages/jasper-2.0.14-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/libpng16-1.6.34-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/jpeg-9c-2-x86_64
haiku-nightlies-x86_64/generated/build_packages/tiff4-4.0.9-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/libwebp-1.0.0-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/gutenprint-5.2.14-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/zlib_source-1.2.11-3-source
haiku-nightlies-x86_64/generated/build_packages/libsolv-0.3.0_haiku_2014_12_22-2-x86_64
haiku-nightlies-x86_64/generated/build_packages/ffmpeg-3.4.2-3-x86_64
haiku-nightlies-x86_64/generated/build_packages/haikuwebkit-1.6.5-1-x86_64
haiku-nightlies-x86_64/generated/build_packages/libsolv_source-0.3.0_haiku_2014_12_22-2-source
haiku-nightlies-x86_64/generated/tmp
haiku-nightlies-x86_64/generated/haiku-nightly-anyboot.iso
haiku-nightlies-x86_64/generated/haiku-nightly.image
haiku-nightlies-x86_64/generated/ReadMeIntro.md
haiku-nightlies-x86_64/generated/nightly-images
haiku-nightlies-x86_64/generated/nightly-images/x86_64
haiku-nightlies-x86_64/generated/ReadMe.md
```


```
$  find buildtools-master-kallisti5-fedora02/  -maxdepth 4 | grep -v attributes
buildtools-master-kallisti5-fedora02/
buildtools-master-kallisti5-fedora02/build
buildtools-master-kallisti5-fedora02/cross-tools-x86
buildtools-master-kallisti5-fedora02/cross-tools-x86_gcc2
buildtools-master-kallisti5-fedora02/cross-tools-x86_64
buildtools-master-kallisti5-fedora02/cross-tools-arm
buildtools-master-kallisti5-fedora02/cross-tools-ppc
buildtools-master-kallisti5-fedora02/cross-tools-m68k
```

**Comment by kallisti5** [comment]
ok.  I just needed more context.  @waddlesplash told me what you guys meant with this one. So pretty much the pwd is build due to a default in buildbot, and during the rebuild of buildtools process via triggering buildtools-master-(worker) it slips into the cleanup steps and throws off the directory cleanup..

**Comment by kallisti5** [comment]
I'm merging this one now... however it won't be on build.haiku-os.org until tomorrow.  I have a builder init running at the moment.

**Comment by kallisti5** [comment]
also, not going to bother putting on buildbot.haiku-os.org.   The codebase differs and won't be around much longer (hopefully)

**Pull request merged**
