### PR TITLE
Updated IP for tnonline.net

### PR DESCRIPTION
**Pull request by Forza-tng**
IPv4 changed from 81.170.131.138 to 158.174.254.104

### CODE REVIEW

**Comment by Forza-tng** [comment]
Hi. Would it be possible to use a DNS name instead of IP, as this would avoid having to do new PRs when IPs change? I could setup a specific subdomain for the rsync client to make it easy to manage.

**Comment by kallisti5** [comment]
actually... you can put hostnames here :laughing: 

These go directly into rsync's config file...
https://github.com/haiku/infrastructure/blob/master/containers/repo-mirror/run#L38

Per the man page:

https://www.man7.org/linux/man-pages/man5/rsyncd.conf.5.html

```
              o      a hostname. A plain hostname is matched against the
                     reverse DNS of the connecting IP (if "reverse
                     lookup" is enabled), and/or the IP of the given
                     hostname is matched against the connecting IP (if
                     "forward lookup" is enabled, as it is by default).
                     Any match will be allowed in.
```

however, it sounds like you need a PTR record defined for the IP for this to work.

**Comment by Forza-tng** [comment]
@kallisti5  I have the posibility for reverse PTR for IPv6 but not IPv4. But perhaps it does not matter if rsync does normal forward lookups? In any case, I don't expect the IP to change again anytime soon.

**Comment by Forza-tng** [comment]
> Is reverse PTR an option for you?

Unfortunately not at this time.  If you can do IPv6, this would be a possibility.

**Comment by pulkomandy** [comment]
Can we at least have the correct IP merged until a better solution is found?

Is there anything to do besides merging this to make it "live"?

**Comment by Forza-tng** [comment]
> Can we at least have the correct IP merged until a better solution is found?
> 
> Is there anything to do besides merging this to make it "live"?

Not that I know.?

**Comment by kallisti5** [comment]
lgtm

**Review by kallisti5 — APPROVED** [review]

**Pull request merged**
