### PR TITLE
Add a container that can run the userguide application, using a

### PR DESCRIPTION
**Pull request by nielx**
combination of fastcgi and nginx.

Notes:
 * I decided that the container will merely contain the elements to
   run the application, but that the application itself is part of the
   persistent storage. This is also mostly due to practical
   considerations, as otherwise the source_docs and export directories
   would need to be linked to a persistent volume. This just feels more
   clean.

### CODE REVIEW

**Comment by kallisti5** [comment]
Looks good to me.  Lets get the images transferred under the haiku docker-hub org.

@nielx , I added you to the docker hub org for Haiku.  Not sure why I hadn't earlier. Same for you @waddlesplash

**Comment by kallisti5** [comment]
errr.. hub.docker.com:   User does not exist: "waddlesplash"

**Comment by waddlesplash** [comment]
@kallisti5 created

**Comment by nielx** [comment]
Pushed all the images to the Haiku account (committed this directly)

**Comment by kallisti5** [comment]
@nielx You can create automatic builds @ hub by clicking the link here:

https://github.com/haiku/infrastructure/blob/master/docs/lifecycle.md
"New automated builds (for new containers) can be created by clicking here"

Seems like it is hidden functionality for Org's now. Every commit to infrastructure will be auto-built into an image.

**Pull request merged**
