### PR TITLE
Add Standard Change Request for HaikuDepot Deployment

### PR DESCRIPTION
**Pull request by nielx**

### CODE REVIEW

**Comment by nielx** [comment]
Hi guys,

I'd like to see whether we can use Github's ticket system as a way to document changes to our infrastructure. This is the first standard change I'd like to propose, so that apl is able to make requests outside of the mailing list and there is a structured way to follow them.

Let me know what you think.

**Comment by kallisti5** [comment]
Looks good to me to be honest.  I haven't really messed with issue templates before, but everything looks reasonable :-)

**Comment by pulkomandy** [comment]
So, should this be merged? I don't have merging powers here so I can't help :)

**Comment by nielx** [comment]
It needs a bit of updating for kubernetes :-)

**Pull request merged**
