### PR TITLE
add real IPs instead of round robin

### PR DESCRIPTION
**Pull request by Tigro**

### CODE REVIEW

**Comment by kallisti5** [comment]
lgtm. Thanks!   I'll apply these within the next 5 minutes or so

**Comment by diversys** [comment]
This is so awesome! Thanks @Tigro! :)

**Comment by evgeny-lityushkin** [comment]
thanks for mirroring Haiku!!!! :-)

**Comment by exstrim401** [comment]
thanks

**Comment by liss21** [comment]
Wow! I've been waiting for two years! Thanks guys!

**Comment by EXL** [comment]
Thanks! 👍🏻

**Comment by kallisti5** [comment]
As a reminder, haiku, and haikuports are also available on [IPFS](http://ipfs.io) which should also work from Russia :-)

/ipns/hpkg.haiku-os.org

**Comment by diversys** [comment]
I haven't found any info about IPFS support at Yandex. @Tigro do you know? Would be so cool! :)
Thanks again! ❤️

**Comment by kallisti5** [comment]
> I haven't found any info about IPFS support at Yandex. @Tigro do you know? Would be so cool! :)

It's more peer-to-peer.
Yandex should play with it... it has built-in de-duplication and would save space + bandwidth :-)


As an example, you can access haiku's repositories on any public (or private / local) ipfs gateway:

* https://de.hpkg.haiku-os.org/
* https://cloudflare-ipfs.com/ipns/hpkg.haiku-os.org
* https://gateway.ipfs.io/ipns/hpkg.haiku-os.org
* etc.

**Comment by diversys** [comment]
@Tigro please let us know when rsync finishes so we could create a promo for this news! :) Kudos to Yandex Department of Hosting Technologies team for doing this!

**Comment by Brunobasta** [comment]
nice and great to know.... hope to see more soon.

**Comment by unarix** [comment]
Thanks for mirroring Haiku!!!!

**Comment by risc-rus** [comment]
Great! Thanks for mirroring Haiku! :-)

**Comment by Tigro** [comment]
> Applied. Let me know if you run into any trouble. Here's the recommended layout:
> 
> * haiku/release  -  rsync://rsync.haiku-os.org:12000/haiku-release
>   
>   * Release images / iso media
> * haiku/haiku    -  rsync://rsync.haiku-os.org:12000/haiku-repositories
>   
>   * Update repositories
> * haiku/haikuports  -   rsync://rsync.haiku-os.org:12000/haikuports-master
>   
>   * Haikuports repositories
> 
> I try to keep the sum of these groomed below ~150 GiB

I have some problems with access. Rsync returns:
---
@ERROR: access denied to haiku-inc from UNKNOWN (172.18.0.1)
--
Strange ip, I think it is our firewall. Is it possible to grant access via basic auth?

**Comment by kallisti5** [comment]
why are you trying to access the haiku-inc share? You won't have access to those :-)

**Comment by Tigro** [comment]
> why are you trying to access the haiku-inc share? You won't have access to those :-)
> 
> Just haiku-release, haiku-repositories, and haikuports-master

Same error:

ashejn@mirror01vla:~$ rsync rsync://rsync.haiku-os.org:12000/haiku-release/
@ERROR: access denied to haiku-release from UNKNOWN (172.18.0.1)
rsync error: error starting client-server protocol (code 5) at main.c(1666) [Receiver=3.1.2]

**Comment by kallisti5** [comment]
Ah ok.   I know what's wrong.  Let me investigate.

**Comment by kallisti5** [comment]
Ok try once more.   tldr; I didn't have IPv6 enabled within our docker install, so all IPv6 requests were getting translated to IPv4 internally (thus rsync couldn't see your connecting address)

If you get the same error again, i'll need to dig a little deeper into making sure IPv6 is enabled on our ingress controller.

**Comment by Tigro** [comment]
Unfortunately the same error  from all my hosts.

**Comment by kallisti5** [comment]
groan.  Ok.

So, we're using Docker swarm for a few years now.  Docker swarm no longer supports IPv6 addressing as of docker-compose 3.x. (I want to move to k8s... just need more time in the day lol)

I'm going to disable the AAAA record for rsync.haiku-os.org.  That should at least temporarily fix the issue.

@Tigro i'm assuming the yandex rsync scraping nodes have an IPv4 address as well as IPv6?

**Comment by kallisti5** [comment]
Complete.

The TTL of rsync.haiku-os.org is 3600, so it'll take up to an hour to show up.   We'll need to update this commit to include the IPv4 addresses of yandex.   You can leave the IPv6 addresses since they will work in theory once we switch over to kubernetes in the future.

**Comment by Tigro** [comment]
> i'm assuming the yandex rsync scraping nodes have an IPv4 address as well as IPv6?

We use NAT64 to get access ipv4 hosts. So there is not real ipv4 addresses on our nodes:(

Maybe basic auth?

**Comment by kallisti5** [comment]
Ah.   Ok.    I'll have to figure out a method to do this.

All of our rsync stuff is automated around whitelisting source IP's.  We have quite a few organizations rsyncing under the current design.

**Comment by diversys** [comment]
Is this possible now?

**Comment by diversys** [comment]
@kallisti5 any news on this one?

**Comment by kallisti5** [comment]
Hm. this one is possible in theory.    We switched to Proxy protocol support in our load balancers earlier in the year with the move to kubernetes.

Let me look into it..

**Comment by kallisti5** [comment]
it appears digitalocean's load balancers don't support ipv6? :grimacing:     I've opened a support ticket to ask.

**Comment by kallisti5** [comment]
Actually, i already had a response:

```
I completely understand your requirements here. Unfortunately we don't support IPv6 address for the Load balancers. We apologize for the inconvenience caused. Our product team always look for such feature request and product feedback, I request you to vote/add on the idea here and subscribe for updates :
```

*sigh*

Here's the "idea": https://ideas.digitalocean.com/network/p/ipv6-for-load-balancers   Vote there and help me out :laughing:

**Pull request merged**
